# Numpy 
To handle large array of data. It is of list datatype in python. But the values in a list can vary in datatype in python but the values in the list should be same for numpy. If not it would try to upcast or throw error.

To import and check the version of the numpy

In [1]:
import numpy as np
np.__version__

'1.20.1'

To get the documentation of the imported module

In [2]:
np?

In [3]:
L1=[]
for i in range(5):
    L1.append(i)
L1

[0, 1, 2, 3, 4]

It tries to upcast the interger to float if possible

In [4]:
L2=[1.0,2,3,4]
np.array(L2)

array([1., 2., 3., 4.])

To specify the datatype explicitly in numpy

In [5]:
np.array([1,2,3,4,5],dtype="float32")

array([1., 2., 3., 4., 5.], dtype=float32)

Multidimensional array

In [6]:
np.array([range(i,i+3) for i in[2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [7]:
#array filled with 0
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
#all filled with 1
np.ones(5, dtype="float32")

array([1., 1., 1., 1., 1.], dtype=float32)

In [9]:
#fill multidimensional array with a particular number
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
#array with equal intervel
arr=np.arange(3,10,2)
print(arr)
arr1=np.arange(0,20,2)
print(arr1)

[3 5 7 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [12]:
#split two numbers into given times
np.linspace(0,1,5,dtype='float32') 
# or use np.<datatype object> eg. np.linspace(0,1,5,dtype=np.int16)

array([0.  , 0.25, 0.5 , 0.75, 1.  ], dtype=float32)

In [13]:
#creates a 3x3 uniformly distributed matrix between 0 to 1.
#study for uniform matrix
np.random.random((3,3))

array([[0.05831545, 0.24475049, 0.66815605],
       [0.90472509, 0.66280864, 0.61267288],
       [0.94312071, 0.32502828, 0.44592997]])

In [14]:
#create a 3x3 matrix with mean as 4 and standard deviation as 5
np.random.normal(4,5,(3,3))

array([[ 6.8022615 , 13.85286305,  9.1812738 ],
       [ 9.00679629,  6.75942512, 16.23768938],
       [-1.77057675,  7.43236626,  5.52581996]])

In [15]:
#print matrix with random numbers between 0 to 10
np.random.randint(0,10,(3,3))

array([[0, 7, 6],
       [4, 8, 8],
       [9, 3, 3]])

In [16]:
#create an empty uninitialized array with 3 elements with value at the memory location
np.empty(2)

array([3.05175852e-05, 7.81250184e-03])

# Basics of Numpy array 

We will be using seed() to reproduce the values at any run. If we give a seed value and run the program any number of times, we would be getting the same random numbers generated. A seed can be number like 0,1,20 or string like 'hello','hi'. We use 0 as argument for seed()

## Attributes of numpy array
Every array has its dimensions, shape, size, memory and datatype.

In [17]:
np.random.seed(0)
x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))
print("no of dimentions of x3 : ",x3.ndim)
print("shape of x3 : ",x3.shape)
print("size of x3 : ", x3.size)
print("data type of x3 : ",x3.dtype)
print("each item size of x3 : ",x3.itemsize," bytes")
print("entire matrix size of x3 : ",x3.nbytes,"bytes")

no of dimentions of x3 :  3
shape of x3 :  (3, 4, 5)
size of x3 :  60
data type of x3 :  int32
each item size of x3 :  4  bytes
entire matrix size of x3 :  240 bytes


## Array indexing

In [18]:
print(x1[0])
print(x1[1])
print(x1[-1])
print(x1[-5])

5
0
9
0


In [19]:
print("x2 : ",x2)
print("printing 0th row of a 2d array : ", x2[0])
print(x2[0,3])
print(x2[2,-3])
# we can also modify the array using the index
x2[0,0] = 9
print("modified x2 : ",x2)

x2 :  [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
printing 0th row of a 2d array :  [3 5 2 4]
4
6
modified x2 :  [[9 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


Numpy arrays are of same datatype so if we try to add 3.14 in the beginning of the array it silently truncates as 3 !!!

## Slicing an array
slicing notation (:)\
x[start:stop:step]\
always the start must be lesser than the stop if not it gives [] as result

In [20]:
x1 = np.array(range(10))
print(x1)
print("first 5 elements",x1[:5])
print("5th index to last element",x1[5:])
print("print 4th index to 6th index ",x1[4:7])
print("numbers in even indexed position ",x1[::2])
print("numbers in odd indexed position ",x1[1::2])
print("print 3 alternate numbers from 2nd index ",x1[2::3])

[0 1 2 3 4 5 6 7 8 9]
first 5 elements [0 1 2 3 4]
5th index to last element [5 6 7 8 9]
print 4th index to 6th index  [4 5 6]
numbers in even indexed position  [0 2 4 6 8]
numbers in odd indexed position  [1 3 5 7 9]
print 3 alternate numbers from 2nd index  [2 5 8]


Caution when the step value is negative then the start and stop are swapped

In [21]:
print("positive step : ",x1[0:10:1])
print("negative stpe : ",x1[::-1])

positive step :  [0 1 2 3 4 5 6 7 8 9]
negative stpe :  [9 8 7 6 5 4 3 2 1 0]


Multidimensional array slicing\
Operation validation is done by row,col

In [22]:
np.random.seed(0)
x2 = np.random.randint(10,size=(3,4))
print("x2:",end='\n')
print(x2)
print("first 3 rows and columns")
print(x2[:3,:2])
print("print alternate rows")
print(x2[::2,:])
print("alternate columns")
print(x2[:,::2])

x2:
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
first 3 rows and columns
[[5 0]
 [7 9]
 [2 4]]
print alternate rows
[[5 0 3 3]
 [2 4 7 6]]
alternate columns
[[5 3]
 [7 3]
 [2 7]]


In [23]:
print("reverse the row values")
print(x2[::-1])
print("reverse the col values")
print(x2[:,::-1])
print("extracting 2nd col")
print(x2[:,1])

reverse the row values
[[2 4 7 6]
 [7 9 3 5]
 [5 0 3 3]]
reverse the col values
[[3 3 0 5]
 [5 3 9 7]
 [6 7 4 2]]
extracting 2nd col
[0 9 4]


## Sub-array as no-copy
Working without a copy affects the original array even though we work on a subarray.

In [24]:
print("Original x2")
print(x2)

Original x2
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [25]:
x2_sub = x2[:2,:3]
print("sub array x2_sub")
print(x2_sub)
# On changing the sub array the original array changes.
print("On changing the sub array the original array changes")
x2_sub[0,0]=25
print(x2)

sub array x2_sub
[[5 0 3]
 [7 9 3]]
On changing the sub array the original array changes
[[25  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]


## Creating a copy of an array
Working on copy of the array does not affect the original array

In [26]:
print("Original x2")
print(x2)

Original x2
[[25  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]


In [27]:
x2_sub_copy = x2[:2,:3].copy()
print("x2_sub_copy")
print(x2_sub_copy,end='\n\n')
x2_sub_copy[0,1] = 33
#on changing the copy the original array is unaffected
print(x2_sub_copy,end='\n\n')
print(x2)

x2_sub_copy
[[25  0  3]
 [ 7  9  3]]

[[25 33  3]
 [ 7  9  3]]

[[25  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]


# Reshaping an array

In [28]:
grid = np.random.randint(9,size=9)
grid

array([8, 8, 1, 6, 7, 7, 8, 1, 5])

In [29]:
grid.reshape((3,3))

array([[8, 8, 1],
       [6, 7, 7],
       [8, 1, 5]])

In [30]:
grid.reshape(9)

array([8, 8, 1, 6, 7, 7, 8, 1, 5])

# How to read a 3d matrix 
Normally a 3d matrix is a collection of 2d matrix. Read the matrix as 2X(3X4)`

In [31]:
np.random.randint(9,size=(2,3,4))

array([[[8, 4, 3, 0],
        [3, 5, 0, 2],
        [3, 8, 1, 3]],

       [[3, 3, 7, 0],
        [1, 0, 4, 7],
        [3, 2, 7, 2]]])

In [32]:
#using reshape to 
print(grid.reshape(1,1,9),end='\n\n')
print(grid.reshape(1,9,1),end='\n\n')
print(grid.reshape(9,1,1),end='\n\n')

[[[8 8 1 6 7 7 8 1 5]]]

[[[8]
  [8]
  [1]
  [6]
  [7]
  [7]
  [8]
  [1]
  [5]]]

[[[8]]

 [[8]]

 [[1]]

 [[6]]

 [[7]]

 [[7]]

 [[8]]

 [[1]]

 [[5]]]



## New axis in slicing operation
Suppose we have a 3d matrix with dimensions 2,3,4 then\
k[:,np.newaxis] makes it as 4d with (2,1,3,4)\
k[np.newaxis,:] makes it as 4d with (1,2,3,4)\
k[:,:,np.newaxis,:] makes it as (2,3,1,4)\
In short it adds a new axis and reshapes the dimension of a matrix where we specify


In [33]:
k=np.array([1,2,3,4])
k.shape

(4,)

In [34]:
k[:,np.newaxis]
k.shape

(4,)

In [35]:
k=np.random.randint(9,size=(2,3,4))
k.shape

(2, 3, 4)

In [36]:
k=k[:,:,np.newaxis,:]
k.shape

(2, 3, 1, 4)

In [37]:
k=k[:,:,np.newaxis,:]
k.shape

(2, 3, 1, 1, 4)

## Array concatenation
np.concatenate - mostly prefered for 1d array\
np.hstack(horizontal stack) and np.vstack(vertical stack) - prefered for multidimensional array

In [44]:
x = np.array([1,2,3])
y = np.array([3,4,5])
z = np.array([
    [11],
    [99]
])
np.concatenate([x, x])

array([1, 2, 3, 1, 2, 3])

In [47]:
np.vstack([x,y])

array([[1, 2, 3],
       [3, 4, 5]])

In [48]:
np.hstack([np.vstack([x,y]),z])

array([[ 1,  2,  3, 11],
       [ 3,  4,  5, 99]])

In [52]:
grid = np.array([[1,2,3],[4,5,6]])
print(np.concatenate([grid,grid]),end="\n\n") #same as vstack
print(np.concatenate([grid,grid],axis=1)) #same as hstack

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [54]:
z = np.array([[[1,2,3],[1,2,3]],[[4,5,6],[4,5,6]]])
z

array([[[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 5, 6]]])

In [56]:
np.dstack([z,z]) #concatenates along 3rd axis

array([[[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]],

       [[4, 5, 6, 4, 5, 6],
        [4, 5, 6, 4, 5, 6]]])

In [57]:
np.concatenate([z,z],axis=2) #same as dstack

array([[[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]],

       [[4, 5, 6, 4, 5, 6],
        [4, 5, 6, 4, 5, 6]]])